version: '3.4'

services:
    app:
        image: docker-dev-tb-mw-ecom-next
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        volumes:
            - ./pages:/app/pages
            - ./public:/app/public
            - ./styles:/app/styles
