version: '3.4'

services:
    app:
        image: docker-prod-tb-mw-ecom-next
        build:
            context: .
            dockerfile: Dockerfile.production
        ports:
            - 3000:3000
